server:
  port: 8083
spring:
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        instanceId: ${spring.application.name}:${random.value}
        preferIpAddress: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_DB_HOST:localhost:5434}/${POSTGRES_DB_NAME:calculate_db}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:sa}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
#    show-sql: true