server:
  port: 8765
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: import-service
          uri: lb://import-service
          predicates:
            - Path=/import/**
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        instanceId: ${spring.application.name}:${random.value}

#springdoc:
#  swagger-ui:
#    use-root-path: true
#    urls:
#      - name: import-service
#        url: /import-service/v3/api-docs
#
#    urls:
#      -
