server:
  port: 8082
spring:
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        instanceId: ${spring.application.name}:${random.value}
#        hostname=: ${spring.application.name}
#        preferIpAddress: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_DB_HOST:localhost:5433}/${POSTGRES_DB_NAME:import_db}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:sa}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
#    show-sql: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB