server:
  port: 8082
spring:
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        instanceId: ${spring.application.name}:${random.value}
#        hostname: ${HOSTNAME:localhost} - использовать если из docker передаем IP хоста
##        hostname: ${spring.application.name} - используем если прописать в файле hosts имя сервиса
        preferIpAddress: false
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9093}
    max:
      request:
        size: 10000000
  datasource:
    url: jdbc:postgresql://${POSTGRES_DB_HOST:localhost:5433}/${POSTGRES_DB_NAME:import_db}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:sa}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
  #    show-sql: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  docker:
    host: ${HOSTNAME:http://localhost:8765/import-service}
topic:
  name: t.call