--liquibase formatted sql

--changeset igor:1

CREATE TABLE IF NOT EXISTS calls
(
    id              INT8 GENERATED BY DEFAULT AS IDENTITY,
    owner_number    VARCHAR(255)   NOT NULL,
    call_service    VARCHAR(255)   NOT NULL,
    call_date_time  TIMESTAMP      NOT NULL,
    code            VARCHAR(40),
    call_time       VARCHAR(20)    NOT NULL,
    number          VARCHAR(32)    NOT NULL,
    sum             NUMERIC(19, 4) NOT NULL,
    short_number    VARCHAR(40)    NOT NULL,
    day_of_week     INT4           NOT NULL,
    mobile_operator VARCHAR(10)    NOT NULL,
    PRIMARY KEY (id)
);

--changeset igor:2

CREATE TABLE IF NOT EXISTS call_service
(
    id                    INT8 GENERATED BY DEFAULT AS IDENTITY,
    owner_number          VARCHAR(255)   NOT NULL,
    call_service_name     VARCHAR(255)   NOT NULL,
    call_time             VARCHAR(20)    NOT NULL,
    vat_tax               VARCHAR(40),
    invoice_date          DATE           NOT NULL,
    number                INT8           NOT NULL,
    sum                   NUMERIC(19, 4) NOT NULL,
    one_time_call_service BOOLEAN        NOT NULL,
    PRIMARY KEY (id)
);

----changeset igor:3

CREATE TABLE IF NOT EXISTS one_time_call_service
(
    id                         INT8 GENERATED BY DEFAULT AS IDENTITY,
    one_time_call_service_name VARCHAR(255) NOT NULL,
    creation_date              TIMESTAMP    NOT NULL,
    PRIMARY KEY (id)
);

----changeset igor:4

CREATE TABLE IF NOT EXISTS import_periods
(
    id              INT8 GENERATED BY DEFAULT AS IDENTITY,
    period          VARCHAR(255) NOT NULL,
    creation_date   TIMESTAMP    NOT NULL,
    mobile_operator VARCHAR(10)  NOT NULL,
    PRIMARY KEY (id)
);

----changeset igor:5

CREATE TABLE IF NOT EXISTS monthly_all_service_mts
(
    id                        INT8 GENERATED BY DEFAULT AS IDENTITY,
    number                    VARCHAR(255)   NOT NULL,
    owner                     VARCHAR(255)   NOT NULL,
    monthly_call_service_name VARCHAR(255)   NOT NULL,
    invoice_date              DATE           NOT NULL,
    start_date                DATE           NOT NULL,
    end_date                  DATE           NOT NULL,
    sum                       NUMERIC(19, 4) NOT NULL,
    sum_with_nds              NUMERIC(19, 4) NOT NULL,
    PRIMARY KEY (id)
);

----changeset igor:6

CREATE TABLE IF NOT EXISTS tariff_by_number
(
    id              INT8 GENERATED BY DEFAULT AS IDENTITY,
    number          VARCHAR(255) NOT NULL,
    owner           VARCHAR(255) NOT NULL,
    tariff_name     VARCHAR(255) NOT NULL,
    start_date_time TIMESTAMP    NOT NULL,
    end_date_time   TIMESTAMP    NOT NULL,
    PRIMARY KEY (id)
);

----changeset igor:7

CREATE TABLE IF NOT EXISTS all_expenses_by_phone_number
(
    id           INT8 GENERATED BY DEFAULT AS IDENTITY,
    number       VARCHAR(255)   NOT NULL,
    owner        VARCHAR(255)   NOT NULL,
    invoice_date DATE           NOT NULL,
    sum          NUMERIC(19, 4) NOT NULL,
    sum_with_nds NUMERIC(19, 4) NOT NULL,
    PRIMARY KEY (id)
);