spring:
  application:
    name: import-service
  config:
    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:8888}
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${random.value}