server:
  port: 8888
spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${random.value}